name: Build VSIX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install
      working-directory: nucleo-debugger
    - name: Install vsce
      run: yarn global add vsce  
      working-directory: nucleo-debugger

    - name: Build VSIX package
      run: vsce package
      working-directory: nucleo-debugger

    - name: Upload VSIX package
      uses: actions/upload-artifact@v2
      with:
        name: my-extension.vsix
        path: nucleo-debugger/*.vsix
