name: Release VSIX
on: 
    release:
      types:
        - created
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install
      working-directory: nucleo-debugger
    - name: Install vsce
      run: yarn global add vsce  
      working-directory: nucleo-debugger

    - name: Build VSIX package
      run: vsce package
      working-directory: nucleo-debugger
    
    - run: mkdir out/
    
    - run: mv ./nucleo-debugger/*.vsix out/
    
    - run: mv ./prova_test/es2/nucleo/.vscode/tasks.json out/ 
    
    - run: mv ./prova_test/es2/nucleo/.vscode/launch.json out/
    
    - run: mv ./prova_test/es2/nucleo/gdbinitvscode out/
    
    - name: Release build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: "./out/*"
