name: Extension Package
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Package VS Code Extension
        # You may pin to the exact commit or the version.
        # uses: nhedger/package-vscode-extension@102a29378b80b78b38adfa820c41387f406aa4f3
          uses: nhedger/package-vscode-extension@v1
          with:
            # Path to the unbundled extension.
            extensionPath: /nucleo-debugger
            # Path to the generated VSIX package.
            packagePath: /nucleo-debugger/
            # Base URL for links detected in Markdown files.
            #baseContentUrl: # optional
            # Base URL for images detected in Markdown files.
            #baseImagetUrl: # optional
            # GitHub branch used to publish the package. Used to automatically infer the base content and images URI.
            useYarn: true
          
